openapi: 3.0.0
info:
  title: Smart Matching
  version: '1.0'
servers:
  - url: 'https://app.lunch-lottery.com'
paths:
  /optin:
    post:
      summary: Smart matching Session Opt-In
      operationId: post-optin
      responses:
        '200':
          description: OK
      description: optin for a match session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                matchSessionId:
                  type: number
                  description: this uniquely identifies the matching session
                profile:
                  $ref: '#/components/schemas/profile'
              required:
                - matchSessionId
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: key to be passed to have access to the endpoint
          required: true
components:
  schemas:
    profile:
      title: profile
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
      required:
        - firstName
        - email
        - phone
      description: Participant profile data structure
