openapi: 3.0.0
info:
  title: Smart Matching
  version: '1.0'
servers:
  - url: 'https://app.lunch-lottery.com'
paths:
  /optin:
    post:
      summary: Opt-In
      operationId: post-optin
      responses:
        '200':
          description: OK - all good
        '400':
          description: Bad Request if something is wrong with the body or the headers
      description: optin for a match session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                matchSessionId:
                  type: number
                profile:
                  $ref: '#/components/schemas/profile'
              required:
                - matchSessionId
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: unique key per lunch
components:
  schemas:
    profile:
      title: profile
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
      required:
        - firstName
        - email
        - phone
